### ISSUE TITLE
Option for XMLEncoder not to self-close tags?

### ISSUE THREAD

**Issue by DJBen** [MaxDesiatov/XMLCoder#135]
Hi I try to find ways to make XMLEncoder NOT to produce self-closing tags.

i.e. I would like `<tag id="1"></tag>` rather than `<tag id="1" />`. Do we have a way to customize this?

Thank you

**Comment by MaxDesiatov** [comment]
Hi @DJBen, within XMLCoder we treat both cases differently, since a self-closed tag indicates an absence of a value, while the lack of it means an empty value (e.g. an empty string). In my opinion the simplest solution would be to leverage [the value intrinsic](https://github.com/MaxDesiatov/XMLCoder#coding-key-value-intrinsic):

```
struct Tag: Codable {
  let id: Int
  let value: String = ""

  enum CodingKeys: String, CodingKey {
    case value = ""
  }
    
  static func nodeEncoding(forKey key: CodingKey) -> XMLEncoder.NodeEncoding {
    switch key {
      case CodingKeys.id:
        return .attribute
      default:
        return .element
      }
  }
}
```

**Comment by DJBen** [comment]
That sounds good. Thanks.
