### ISSUE TITLE
Add Swift Version to Podspec

### ISSUE THREAD

**Issue by khoogheem** [MaxDesiatov/XMLCoder#57]
```
s.swift_version       = '4.0'
```

should be added to podSpec

**Comment by khoogheem** [comment]
my understanding and from that read is that the .swift-version is just for lint and push to trunk.
The swift version inside of the spec helps with the target building version when bringing into projects

**Comment by MaxDesiatov** [comment]
To clarify, I've never tested XMLCoder with Swift 4.0 or Swift 4.1 previously. Tests would almost certainly fail in 4.0 as they rely on `Equatable` implementations provided by the compiler, which became available in Swift 4.1. We might be ok with setting this value in the podspec to 4.1, but could you please clarify whether you've chosen specifically 4.0 in the initial report on purpose?

I'm not against adding it to the podspec, but we need to be sure it's the correct version. Also we'd need to run the tests against all possible versions. Adding `s.swift_version = '4.2'` instead of `s.swift_version = '4.0'` would make a lot of things easier.

**Comment by khoogheem** [comment]
4.2 seems to make more sense.  

Would then we also want to change that in the Package to use the 4.2 tools
