### ISSUE TITLE
Trimmed whitespace on decoding String

### ISSUE THREAD

**Issue by TheFlow95** [MaxDesiatov/XMLCoder#94]
I had another issue with the library when decoding strings. For example if I have a string with a whitespace at the end in my XML, it will get trimmed when decoding but I don't want this behavior.

Moreover, when an element contains an empty string, it is automatically interpreted as nil.

**Comment by MaxDesiatov** [comment]
Hi @TheFlow95, thanks for reporting this. The conversion of empty strings to `nil` is now fixed in #92. As for trimming the whitespaces, I think the best way forward would be to add a property on `XMLDecoder` like `trimValueWhitespaces` to turn the trimming off, while the default value would be `true` for backward compatibility.

**Comment by MaxDesiatov** [comment]
This is now fixed in `master` and will be included in 0.5 release, which I'm going to tag soon.

**Comment by MaxDesiatov** [comment]
`trimValueWhitespaces` has also been added in #92 and is now available in `master`.
